ARG NODE_VERSION="22"
ARG APP_NAME="cms"

ARG CMS_PORT="3001"
ARG DESIGN_SYSTEM_PORT="3002"
ARG WEBSITE_PORT="3003"

# -------- BASE --------
FROM node:${NODE_VERSION}-alpine AS base

ENV NODE_ENV="production"
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV NEXT_TELEMETRY_DISABLED="1"

# -------- BUILD --------
FROM base AS build

ARG APP_NAME

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN corepack enable

# Installer toutes les dépendances internes nécessaires au package + devDeps pour build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --filter "${APP_NAME}..." --frozen-lockfile --ignore-scripts

# Build + deploy
RUN pnpm run build --filter "${APP_NAME}"
RUN pnpm deploy --filter "${APP_NAME}" --prod "/prod/${APP_NAME}"

# -------- CMS (Next.js standalone) --------
FROM base AS cms
ARG APP_NAME
ARG CMS_PORT

ENV PORT=$CMS_PORT

# Mise à jour Alpine minimale
RUN apk --no-cache -U upgrade

WORKDIR /app
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=build /app/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=build --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=build --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
CMD HOSTNAME="0.0.0.0" node server.js


# -------- DESIGN SYSTEM --------
FROM base AS design-system
WORKDIR /prod/design-system

COPY --from=build /prod/design-system ./

ARG DESIGN_SYSTEM_PORT
ENV PORT=$DESIGN_SYSTEM_PORT
EXPOSE $DESIGN_SYSTEM_PORT

CMD ["pnpm", "start"]


# -------- WEBSITE --------
FROM base AS website
WORKDIR /prod/website

COPY --from=build /prod/website ./

ARG WEBSITE_PORT
ENV PORT=$WEBSITE_PORT
EXPOSE $WEBSITE_PORT

CMD ["pnpm", "start"]
